{"uid":"cd0a8114d2fd2a88","name":"Получение информации о пользователе","fullName":"tests.user.test_user.TestUser#test_get_user","historyId":"c838d696e7ae4a955eeefdd9f9d3bf99","time":{"start":1744327889448,"stop":1744327894476,"duration":5028},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200","statusTrace":"self = <test_user.TestUser object at 0x7f3c7d7295e0>\nclient = <src.models.client.Client object at 0x7f3c7d72a6f0>\nuser_helper = <src.func.user.helpers.UserHelper object at 0x7f3c7d740530>\nuser_data = User(id=2694, username='lucasrodriguez', first_name='Jasmine', last_name='Gardner', email='wheelerrobert@example.net', password='j3esIzIH&s', phone='+1-656-873-7390x95868', user_status=2)\n\n    @allure.title(\"Получение информации о пользователе\")\n    def test_get_user(self, client, user_helper, user_data):\n        user_helper.create_user(client, user_data)\n    \n        time.sleep(5)\n    \n        with allure.step(\"Получение информации о пользователе\"):\n>           response = user_helper.get_user(client, user_data.username)\n\ntests/user/test_user.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/func/user/helpers.py:24: in get_user\n    CustomAsserts.check_status_code(response, expected_status_code)\nsrc/tech/custom_asserts.py:53: in check_status_code\n    _check_status_code(response, expected_status_code)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>, expected_code = 200\n\n    @step(f\"Статус код = {expected_status_code}\")\n    def _check_status_code(resp, expected_code):\n>   \tassert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\nE    AssertionError: Статус код 404 не равен ожидаемому 200\n\nsrc/tech/custom_asserts.py:51: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1744327868637,"stop":1744327868639,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"client","time":{"start":1744327868639,"stop":1744327868639,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_helper","time":{"start":1744327889392,"stop":1744327889393,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_data","time":{"start":1744327889446,"stop":1744327889447,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200","statusTrace":"self = <test_user.TestUser object at 0x7f3c7d7295e0>\nclient = <src.models.client.Client object at 0x7f3c7d72a6f0>\nuser_helper = <src.func.user.helpers.UserHelper object at 0x7f3c7d740530>\nuser_data = User(id=2694, username='lucasrodriguez', first_name='Jasmine', last_name='Gardner', email='wheelerrobert@example.net', password='j3esIzIH&s', phone='+1-656-873-7390x95868', user_status=2)\n\n    @allure.title(\"Получение информации о пользователе\")\n    def test_get_user(self, client, user_helper, user_data):\n        user_helper.create_user(client, user_data)\n    \n        time.sleep(5)\n    \n        with allure.step(\"Получение информации о пользователе\"):\n>           response = user_helper.get_user(client, user_data.username)\n\ntests/user/test_user.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/func/user/helpers.py:24: in get_user\n    CustomAsserts.check_status_code(response, expected_status_code)\nsrc/tech/custom_asserts.py:53: in check_status_code\n    _check_status_code(response, expected_status_code)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>, expected_code = 200\n\n    @step(f\"Статус код = {expected_status_code}\")\n    def _check_status_code(resp, expected_code):\n>   \tassert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\nE    AssertionError: Статус код 404 не равен ожидаемому 200\n\nsrc/tech/custom_asserts.py:51: AssertionError","steps":[{"name":"Создание пользователя","time":{"start":1744327889448,"stop":1744327889458,"duration":10},"status":"passed","steps":[{"name":"Статус код = 200","time":{"start":1744327889458,"stop":1744327889458,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"resp","value":"<Response [200]>"},{"name":"expected_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"5a93f30d46790a2c","name":"Request","source":"5a93f30d46790a2c.txt","type":"text/plain","size":40},{"uid":"b653ef97c7259e00","name":"Request headers","source":"b653ef97c7259e00.json","type":"application/json","size":196},{"uid":"8ed519da28c02de0","name":"Request body","source":"8ed519da28c02de0.json","type":"application/json","size":222},{"uid":"508c3567aa9d6541","name":"Response status code","source":"508c3567aa9d6541.txt","type":"text/plain","size":3},{"uid":"2a573febe131a984","name":"Response Headers","source":"2a573febe131a984.json","type":"application/json","size":357},{"uid":"819c34e12d31d1cd","name":"Response body","source":"819c34e12d31d1cd.json","type":"application/json","size":59}],"parameters":[{"name":"client","value":"<src.models.client.Client object at 0x7f3c7d72a6f0>"},{"name":"data","value":"User(id=2694, username='lucasrodriguez', first_name='Jasmine', last_name='Gardner', email='wheelerrobert@example.net', password='j3esIzIH&s', phone='+1-656-873-7390x95868', user_status=2)"},{"name":"expected_status_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":6,"hasContent":true,"attachmentStep":false},{"name":"Получение информации о пользователе","time":{"start":1744327894458,"stop":1744327894475,"duration":17},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/home/runner/work/python-pytest-api/python-pytest-api/tests/user/test_user.py\", line 44, in test_get_user\n    response = user_helper.get_user(client, user_data.username)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/func/user/helpers.py\", line 24, in get_user\n    CustomAsserts.check_status_code(response, expected_status_code)\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 53, in check_status_code\n    _check_status_code(response, expected_status_code)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Получение информации о пользователе","time":{"start":1744327894459,"stop":1744327894475,"duration":16},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/func/user/helpers.py\", line 24, in get_user\n    CustomAsserts.check_status_code(response, expected_status_code)\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 53, in check_status_code\n    _check_status_code(response, expected_status_code)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Статус код = 200","time":{"start":1744327894475,"stop":1744327894475,"duration":0},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[{"name":"resp","value":"<Response [404]>"},{"name":"expected_code","value":"200"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"d20baca09970506c","name":"Request","source":"d20baca09970506c.txt","type":"text/plain","size":54},{"uid":"a23b6000fd48cf48","name":"Request headers","source":"a23b6000fd48cf48.json","type":"application/json","size":169},{"uid":"35daa62e6ff4d2ca","name":"Response status code","source":"35daa62e6ff4d2ca.txt","type":"text/plain","size":3},{"uid":"d978e16289fed60e","name":"Response Headers","source":"d978e16289fed60e.json","type":"application/json","size":357},{"uid":"f1f7dd747809b766","name":"Response body","source":"f1f7dd747809b766.json","type":"application/json","size":65}],"parameters":[{"name":"client","value":"<src.models.client.Client object at 0x7f3c7d72a6f0>"},{"name":"username","value":"'lucasrodriguez'"},{"name":"expected_status_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":11,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"User"},{"name":"epic","value":"Petstore API"},{"name":"tag","value":"user"},{"name":"parentSuite","value":"tests.user"},{"name":"suite","value":"test_user"},{"name":"subSuite","value":"TestUser"},{"name":"host","value":"fv-az1065-663"},{"name":"thread","value":"2296-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.user.test_user"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":["user"]},"source":"cd0a8114d2fd2a88.json","parameterValues":[]}