{"uid":"da1ffdc9e3849a91","name":"Удаление пользователя","fullName":"tests.user.test_user.TestUser#test_delete_user","historyId":"c34960d1aa5684da554c1da603fce9e5","time":{"start":1744327894299,"stop":1744327899366,"duration":5067},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200","statusTrace":"self = <test_user.TestUser object at 0x7fed95840b90>\nuser_helper = <src.func.user.helpers.UserHelper object at 0x7fed958658e0>\nuser_data = User(id=5156, username='millssarah', first_name='Raymond', last_name='Warner', email='heathermendoza@example.org', password='%R%kTGLvN3', phone='453-397-6977x33227', user_status=1)\nclient = <src.models.client.Client object at 0x7fed96725340>\n\n    @allure.title(\"Удаление пользователя\")\n    def test_delete_user(self, user_helper, user_data, client):\n        user_helper.create_user(client, user_data)\n    \n        time.sleep(5)\n    \n        with allure.step(\"Удаление пользователя\"):\n>           response = user_helper.delete_user(client, user_data.username)\n\ntests/user/test_user.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/func/user/helpers.py:39: in delete_user\n    CustomAsserts.check_status_code(response, expected_status_code)\nsrc/tech/custom_asserts.py:53: in check_status_code\n    _check_status_code(response, expected_status_code)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>, expected_code = 200\n\n    @step(f\"Статус код = {expected_status_code}\")\n    def _check_status_code(resp, expected_code):\n>   \tassert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\nE    AssertionError: Статус код 404 не равен ожидаемому 200\n\nsrc/tech/custom_asserts.py:51: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1744327868637,"stop":1744327868639,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"client","time":{"start":1744327868639,"stop":1744327868639,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_data","time":{"start":1744327894297,"stop":1744327894299,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_helper","time":{"start":1744327894297,"stop":1744327894297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200","statusTrace":"self = <test_user.TestUser object at 0x7fed95840b90>\nuser_helper = <src.func.user.helpers.UserHelper object at 0x7fed958658e0>\nuser_data = User(id=5156, username='millssarah', first_name='Raymond', last_name='Warner', email='heathermendoza@example.org', password='%R%kTGLvN3', phone='453-397-6977x33227', user_status=1)\nclient = <src.models.client.Client object at 0x7fed96725340>\n\n    @allure.title(\"Удаление пользователя\")\n    def test_delete_user(self, user_helper, user_data, client):\n        user_helper.create_user(client, user_data)\n    \n        time.sleep(5)\n    \n        with allure.step(\"Удаление пользователя\"):\n>           response = user_helper.delete_user(client, user_data.username)\n\ntests/user/test_user.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/func/user/helpers.py:39: in delete_user\n    CustomAsserts.check_status_code(response, expected_status_code)\nsrc/tech/custom_asserts.py:53: in check_status_code\n    _check_status_code(response, expected_status_code)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>, expected_code = 200\n\n    @step(f\"Статус код = {expected_status_code}\")\n    def _check_status_code(resp, expected_code):\n>   \tassert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\nE    AssertionError: Статус код 404 не равен ожидаемому 200\n\nsrc/tech/custom_asserts.py:51: AssertionError","steps":[{"name":"Создание пользователя","time":{"start":1744327894299,"stop":1744327894349,"duration":50},"status":"passed","steps":[{"name":"Статус код = 200","time":{"start":1744327894349,"stop":1744327894349,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"resp","value":"<Response [200]>"},{"name":"expected_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"1f9e185262cdbd11","name":"Request","source":"1f9e185262cdbd11.txt","type":"text/plain","size":40},{"uid":"3c28a85f393bd74d","name":"Request headers","source":"3c28a85f393bd74d.json","type":"application/json","size":196},{"uid":"b83f5b085e1bfc2a","name":"Request body","source":"b83f5b085e1bfc2a.json","type":"application/json","size":215},{"uid":"16f906c73fe6fe9c","name":"Response status code","source":"16f906c73fe6fe9c.txt","type":"text/plain","size":3},{"uid":"20b148468af6f47b","name":"Response Headers","source":"20b148468af6f47b.json","type":"application/json","size":357},{"uid":"8fe0700eff3a9c39","name":"Response body","source":"8fe0700eff3a9c39.json","type":"application/json","size":59}],"parameters":[{"name":"client","value":"<src.models.client.Client object at 0x7fed96725340>"},{"name":"data","value":"User(id=5156, username='millssarah', first_name='Raymond', last_name='Warner', email='heathermendoza@example.org', password='%R%kTGLvN3', phone='453-397-6977x33227', user_status=1)"},{"name":"expected_status_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":6,"hasContent":true,"attachmentStep":false},{"name":"Удаление пользователя","time":{"start":1744327899350,"stop":1744327899365,"duration":15},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/home/runner/work/python-pytest-api/python-pytest-api/tests/user/test_user.py\", line 64, in test_delete_user\n    response = user_helper.delete_user(client, user_data.username)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/func/user/helpers.py\", line 39, in delete_user\n    CustomAsserts.check_status_code(response, expected_status_code)\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 53, in check_status_code\n    _check_status_code(response, expected_status_code)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Удаление пользователя","time":{"start":1744327899350,"stop":1744327899365,"duration":15},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/func/user/helpers.py\", line 39, in delete_user\n    CustomAsserts.check_status_code(response, expected_status_code)\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 53, in check_status_code\n    _check_status_code(response, expected_status_code)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Статус код = 200","time":{"start":1744327899364,"stop":1744327899364,"duration":0},"status":"failed","statusMessage":"AssertionError: Статус код 404 не равен ожидаемому 200\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-pytest-api/python-pytest-api/src/tech/custom_asserts.py\", line 51, in _check_status_code\n    assert resp.status_code == expected_code, f\"Статус код {resp.status_code} не равен ожидаемому {expected_code}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[{"name":"resp","value":"<Response [404]>"},{"name":"expected_code","value":"200"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"5c46018090fad99d","name":"Request","source":"5c46018090fad99d.txt","type":"text/plain","size":53},{"uid":"d190a1d50655a7be","name":"Request headers","source":"d190a1d50655a7be.json","type":"application/json","size":194},{"uid":"225a75b3dea3b084","name":"Response status code","source":"225a75b3dea3b084.txt","type":"text/plain","size":3},{"uid":"79f51f55ac189302","name":"Response Headers","source":"79f51f55ac189302.json","type":"application/json","size":310}],"parameters":[{"name":"client","value":"<src.models.client.Client object at 0x7fed96725340>"},{"name":"username","value":"'millssarah'"},{"name":"expected_status_code","value":"200"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":4,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":4,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":10,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"User"},{"name":"epic","value":"Petstore API"},{"name":"tag","value":"user"},{"name":"parentSuite","value":"tests.user"},{"name":"suite","value":"test_user"},{"name":"subSuite","value":"TestUser"},{"name":"host","value":"fv-az1065-663"},{"name":"thread","value":"2299-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.user.test_user"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":["user"]},"source":"da1ffdc9e3849a91.json","parameterValues":[]}